### ISSUE TITLE
Inconsistency between Vim and terminal

### ISSUE THREAD

**Issue by elmerehbi** [nightsense/night-and-day#2]
Thank you for such a plugin..

I am using Guake terminal. I tried the default solarized dark in Guake. I also installed base16 and tried base16_default_dark which works with sunrise but at sunset the solarized dark is not well displayed.

How do you keep vim and the terminal themes in check?

This is what I currently have in .vimrc:
```
" Base16 Vim://github.com/chriskempson/base16-vim
" requires Base16 Shell: https://github.com/chriskempson/base16-shell
if filereadable(expand("~/.vimrc_background"))
  let base16colorspace=256
  source ~/.vimrc_background
endif

let g:nd_latitude = '50'
" set timeshift for sun-relative timings &
" take care of DST automatically
if strftime("%m") > 2 && strftime("%m") < 10
  let g:nd_timeshift = '120'
else
  let g:nd_timeshift = '7'
endif

" sun-relative timings 
let g:nd_themes = [
  \ ['sunrise+0',    'base16-default-dark', 'dark' ],
  \ ['sunrise+1/2',  'solarized',            'light' ],
  \ ['sunset+0',     'solarized',            'dark'  ],
  \ ]
```

**Comment by nightsense** [comment]
Hi @elmerehbi , I messed around a bit and couldn't get the original Solarized vim theme working in Guake either. I would recommend trying a modernized fork, like [Solarized 8](https://github.com/lifepillar/vim-solarized8) or [flattened](https://github.com/romainl/flattened). You may need `set termguicolors` in your vimrc for these to work.
